### ISSUE TITLE
Ur mods broken

### ISSUE THREAD

**Issue by Cadiboo** [Tfarcenim/Extra-Anvils#15]
https://github.com/Tfarcenim/Extra-Anvils/blob/a3f1c15925221e47236244138a1ade03e0306159/src/main/java/com/tfar/extraanvils/Setup.java#L120

https://www.minecraftforge.net/forum/topic/72692-1122-minecraft-crashing-javalangnullpointerexception-initializing-game/

**Comment by linxuanm** [comment]
Dynamic registration -> bad bad.
Register everything and disable the recipes and hide from creative tab for disabled items -> good good.

**Comment by Tfarcenim** [comment]
that's cute if you think I'm going to do that, byebye now :smile:
