### ISSUE TITLE
[Suggestion] Base/Modern Metals Support

### ISSUE THREAD

**Issue by CuChulainn0** [Tfarcenim/Extra-Anvils#17]
Would you consider adding support for Base Metals and Modern Metals? I'm not necessarily requesting any new anvil types, just compatibility for the materials in the aforementioned mods that overlap with already supported mods like Thermal Foundation (i.e. aluminum, bronze, copper, electrum, invar, iridium, lead, nickel, platinum, silver, steel, tin). I don't personally use Thermal Foundation and would love to have access to more of your anvils in my playthroughs, since your mod is one of my staples. New anvil types for the non-overlapping materials in those mods would be awesome, but I'd be perfectly happy settling for compatibility with the anvils you've already made. Keep up the great work.

**Comment by Tfarcenim** [comment]
Sorry about for taking so long, I redid the config, and removed the hardcoded modid list, you will need to update your config to adjust to the changes, but it should be compatible with most of the pre-programmed anvils.
