### ISSUE TITLE
[1.14.4]Crash on placing stone anvil

### ISSUE THREAD

**Issue by Tommeh1** [Tfarcenim/Extra-Anvils#19]
extraanvils-2.3a.jar
[crash-2019-10-11_20.25.36-server.txt](https://github.com/Tfarcenim/Extra-Anvils/files/3719382/crash-2019-10-11_20.25.36-server.txt)

**Comment by Tfarcenim** [comment]
Accidentally had a hard dependency on Anvil Tweaks, either add anviltweaks or upgrade to 2.4 where it's fixed.

**Comment by Tommeh1** [comment]
I'm aware, that's why i closed it so quickly
