### ISSUE TITLE
Texture for modded materials are broken even if you have a mod that adds the materials it needs [Latest Version] [1.16.5]

### ISSUE THREAD

**Issue by Red-TF2-Sniper** [Tfarcenim/Extra-Anvils#26]
![2021-11-16_10 55 35](https://user-images.githubusercontent.com/91907457/142030809-9dc0ce0b-bccf-465c-8529-5e28c3f7985f.png)
![2021-11-16_10 55 40](https://user-images.githubusercontent.com/91907457/142030815-d5f6fd11-2dfd-47b8-ad2d-0bbacde9ab68.png)

**Comment by Thelnfamous1** [comment]
Per the curseforge page:

> Due to the texture changes, all modded metal anvils are on hold until someone provides textures for them, they still have functional stats though and can be manually enabled if desired with datapacks and resource packs/ or resource loader.

Looks like users will need to supply the textures themselves at the moment if they want to see them render properly in-game.

**Comment by Tfarcenim** [comment]
Not a bug, intended. If someone wants textures for the modded anvils they have to supply it themselves.
