### ISSUE TITLE
[Suggestion] Add in image and issue tab to curseforge page

### ISSUE THREAD

**Issue by DWX12** [Tfarcenim/Extra-Anvils#8]
I know you have one image on your main page, but images of each group of anvils for each supported mod would be great to have in an images section.

The other suggestion is for an issue tab that would link to this issue section instead of having to go through sources.

Thanks for your time, effort, and work spent on making this mod.

**Comment by Tfarcenim** [comment]
too many duplicates for that to work nicely as I'm not capping the copper anvil 10 times

issue link added
