### ISSUE TITLE
[Bug] Extra Anvils not registering Embers Rekindled metals

### ISSUE THREAD

**Issue by DWX12** [Tfarcenim/Extra-Anvils#9]
While looking at my log file, noticed that a number of metals found in Embers Rekindled, are being skipped and not loading. This is with version .8 of Extra Anvils.

Aluminum
Lead
Nickel
Silver

Copper, bronze, electrum, and tin all register just fine, but may be because of other mods I have in my pack such as Forestry, Zen: Foundry, and Gadgetry.

Steel is also not being registered despite it being in Gadgetry.

Thanks again.

**Comment by Tfarcenim** [comment]
sorted
